### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Maggiore#2]
Sai cos'è un file .gitignore?

**Comment by lucifero55** [comment]
si

**Comment by FabioZTessitore** [comment]
allora aggiungilo in modo da non caricare più il file eseguibile (ora devi eliminarlo perché è stato caricato)

**Comment by lucifero55** [comment]
non ricordo come scrivere per far individuare al file .gitignore il file eseguibile

**Comment by FabioZTessitore** [comment]
devi semplicemente scriverci il nome dentro
