### ISSUE TITLE
formattare il codice

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Maggiore#3]
se usi Vim prova a dare questi comandi in sequenza (attenzione a maiuscole e minuscole)

gg                    va alla prima riga
V                     seleziona la riga
G                     va all'ultima riga (selezionando tutto)
=                      formatta il codice

**Comment by FabioZTessitore** [comment]
la formattazione del codice è importante !!!

**Comment by lucifero55** [comment]
fatto, ma non ho capito cosa ha fatto di preciso

**Comment by FabioZTessitore** [comment]
partendo dal presupposto che non hai un file di configurazione di vim (te lo mando per posta tra un attimo), ha tentato di formattare automaticamente il tuo codice. In particolare ha dato una tabulazione a tutte le istruzioni che si trovano dentro ad un blocco `{ ... }`

Se vogliamo usare un metodo comune dovresti fare cosi:
```c
/* quando si crea una funzione mettiamo le parentesi graffe su righe separate */
void foo()
{
  ...
}

/* Quando scriviamo altre istruzioni che richiedono parentesi graffe, continuiamo
 * sullo stesso rigo. La chiusura invece va su rigo a se
 */
if (...) {
  ...
}
```

**Comment by lucifero55** [comment]
fatto

**Comment by FabioZTessitore** [comment]
esattamente cosa avresti fatto?

**Comment by lucifero55** [comment]
ho messo il file e ripetuto la formattazione ma non sembra cambiato nulla

**Comment by FabioZTessitore** [comment]
qualcosa è cambiato, ora non usa le tabulazioni ma un paio di spazi. Però devi mettere le parentesi graffe al loro posto così come ti ho spiegato prima

**Comment by lucifero55** [comment]
così?

**Comment by FabioZTessitore** [comment]
dai un'occhiata a come ho fatto io e andiamo avanti
