### ISSUE TITLE
solo due if

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Maggiore#6]
bastano due if per risolvere il problema non tre ...

**Comment by lucifero55** [comment]
vale la funzione and?

**Comment by FabioZTessitore** [comment]
non è una funzione, cmq no

**Comment by lucifero55** [comment]
fatto

**Comment by FabioZTessitore** [comment]
ok, ma devi spiegarmi quale contorto ragionamento hai fatto per partire dal secondo e non dal primo. Mah

**Comment by lucifero55** [comment]
perchè così non modificavo la if sotto :D

**Comment by FabioZTessitore** [comment]
forza aggiusta

**Comment by lucifero55** [comment]
così va meglio?

**Comment by FabioZTessitore** [comment]
anche se funziona non va bene. Guarda le condizioni delle due if. Vedi la differenza?

**Comment by lucifero55** [comment]
in una c'è la variabile maggiore?

**Comment by FabioZTessitore** [comment]
eh. nell'altra no. Secondo te quale delle due va bene (immagina la cosa in un'ottica futura di ciclo)

**Comment by lucifero55** [comment]
decisamente quella con la variabile maggiore
